[package]
name = "treeportfs-nfs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
treeportfs-core.workspace = true
treeportfs-git.workspace = true
anyhow.workspace = true
async-trait.workspace = true
filetime.workspace = true
nfsserve.workspace = true
tokio.workspace = true
tracing.workspace = true
